name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        KOPANO_SERIAL: ${{ secrets.KOPANO_SERIAL }}
      with:
        name:  registry.meteorit-leipzig.de/kopano
        registry: registry.meteorit-leipzig.de
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        buildargs:  KOPANO_SERIAL
        tag_names: true