name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish
      uses: jerray/publish-docker-action@v1.0.5
      env:
        KOPANO_SERIAL: ${{ secrets.KOPANO_SERIAL }}
      with:
        registry: registry.meteorit-leipzig.de
        repository: kopano
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        build_args:  KOPANO_SERIAL
        auto_tag: true